runtime: nodejs18

instance_class: F2  # Instância flexível para melhor desempenho

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

env_variables:
  NODE_ENV: production  # Define o ambiente de produção

handlers:
  - url: /.*
    script: auto
    secure: always
